version: '3.8'

services:
  frontend:
    build: 
      context: https://github.com/delucadiogo/naoconformidade.git#main:frontend
    ports:
      - "8060:80"
    environment:
      - VITE_API_URL=http://192.168.2.175:3001/api
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: https://github.com/delucadiogo/naoconformidade.git#main:backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Xinxuan99
      - POSTGRES_DB=nao_conformidades
      - JWT_SECRET=SDAFsadFdsfDSFefGth5849846ggseGfgh
      - UPLOAD_FOLDER=uploads
      - PORT=3001
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Xinxuan99
      - POSTGRES_DB=nao_conformidades
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
  uploads:

networks:
  app-network:
    driver: bridge 